# Debug inputs
#       application_folder: "TestForDevHUBImportFlow"
#              application: "TestForDevHUBImportFlow.application"
#               bw6_system: "car-order-system"
#         bw6_project_name: "TestForDevHUBImportFlow"
#  bw6_project_description: ""
#     bw6_project_manifest: ["Manifest-Version: 1.0","Manifest-Version: 1.0",""]
# bw6_project_dependencies: []
#                  repoUrl: "github.com?owner=wibowosaroyo&repo=ImportFlowsRepo"
#                    owner: "group:default/tibco-imported"

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: BW6-Projects
  description: A group for all BW6 Projects
spec:
  type: organization
  profile:
    displayName: BW6 Projects
    email: info@acme.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: bw6
  description: BW6 Domain
spec:
  owner: group:BW6-Projects
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: car-order-system
  description: car-order-system
  annotations:
     github.com/project-slug: https://github.com/wibowosaroyo/ImportFlowsRepo
  tags:
    - tibco-bw6
    - imported 
spec:
  owner: group:BW6-Projects
  domain: bw6
